CREATE DATABASE IF NOT EXISTS DEALERSHIP;

USE DEALERSHIP;

CREATE TABLE IF NOT EXISTS TEST_FORMS (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    company VARCHAR(255) NOT NULL,
    isEmployed BOOLEAN
);